/**
 * Storage strategy for the bearer auth token.
 *
 * Priority:
 *   1. Tauri persistent store (survives Android WebView recycle / app restart)
 *   2. window.localStorage (browser fallback)
 *   3. In-memory map (SSR / first-load before window is available)
 *
 * This matters for Tauri Android: the WebView can be torn down and recreated,
 * which wipes `localStorage`. The Tauri store is the only place that survives
 * a cold app launch on Android.
 */

const AUTH_TOKEN_KEY = "auth-token";

let memoryToken: string | null = null;

let tauriStorePromise: Promise<{
  get: (key: string) => Promise<string | undefined>;
  set: (key: string, value: string) => Promise<void>;
  delete: (key: string) => Promise<boolean>;
} | null> | null = null;

function loadTauriStore() {
  if (tauriStorePromise) return tauriStorePromise;

  tauriStorePromise = (async () => {
    // Best-effort dynamic import so the web-only bundle does not require it.
    try {
      const mod = await import("@tauri-apps/plugin-store");
      // v2 API. The store name "auth" is a filename generated by the plugin
      // (e.g. auth.json) inside the app's data directory.
      const store = await mod.load("auth.json", { autoSave: true, defaults: {} });
      return {
        get: (key) => store.get<string>(key),
        set: (key, value) => store.set(key, value),
        delete: (key) => store.delete(key),
      };
    } catch {
      // Tauri / plugin not available (e.g. running in a regular browser)
      return null;
    }
  })();

  return tauriStorePromise;
}

async function readPersistedToken(): Promise<string | null> {
  const tauri = await loadTauriStore();
  if (tauri) {
    const value = await tauri.get(AUTH_TOKEN_KEY);
    if (value) return value;
  }

  if (typeof window !== "undefined" && window.localStorage) {
    return window.localStorage.getItem(AUTH_TOKEN_KEY);
  }

  return memoryToken;
}

async function writePersistedToken(token: string): Promise<void> {
  memoryToken = token;

  const tauri = await loadTauriStore();
  if (tauri) {
    await tauri.set(AUTH_TOKEN_KEY, token);
  }

  if (typeof window !== "undefined" && window.localStorage) {
    window.localStorage.setItem(AUTH_TOKEN_KEY, token);
  }
}

async function removePersistedToken(): Promise<void> {
  memoryToken = null;

  const tauri = await loadTauriStore();
  if (tauri) {
    await tauri.delete(AUTH_TOKEN_KEY);
  }

  if (typeof window !== "undefined" && window.localStorage) {
    window.localStorage.removeItem(AUTH_TOKEN_KEY);
  }
}

// --- Synchronous API used by the Better-Auth client (token() => string) ---

// Track what's been written this session so synchronous reads return the
// the latest value even before the async store flush completes (relevant for
// the very request that just persisted the token).
let cachedToken = "";

export function getAuthToken(): string {
  if (cachedToken) return cachedToken;

  if (typeof window !== "undefined" && window.localStorage) {
    cachedToken = window.localStorage.getItem(AUTH_TOKEN_KEY) ?? "";
    if (cachedToken) return cachedToken;
  }

  return cachedToken;
}

/**
 * Persist a bearer token. Safe to call from request success handlers; updates
 * both the synchronous cache and the (async) durable Tauri store.
 */
export function persistAuthToken(token: string) {
  if (!token) return;
  cachedToken = token;
  if (typeof window !== "undefined" && window.localStorage) {
    window.localStorage.setItem(AUTH_TOKEN_KEY, token);
  }
  // Fire-and-forget: write to Tauri durable store without blocking the caller.
  void writePersistedToken(token);
}

/**
 * Clear all stored tokens (localStorage + Tauri + memory). Call on sign-out
 * and account deletion.
 */
export async function clearAuthToken() {
  cachedToken = "";
  await removePersistedToken();
}

// --- Optional warm-up helper ---------------------------------------------

/**
 * Hydrate the in-memory cache from the Tauri store at app start. Useful to
 * call from a top-level effect so the first authenticated request has the
 * token available synchronously.
 */
export async function hydrateAuthToken(): Promise<void> {
  const value = await readPersistedToken();
  if (value) cachedToken = value;
}
